name: Docker
on:
  push:

jobs:
  firefox:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" | sed 's|/|-|g' >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/378
          context: ./firefox
          platforms: |-
              linux/amd64
          push: true
          tags: |-
              ghcr.io/${{ github.repository }}:firefox
              ghcr.io/${{ github.repository }}:firefox-${{ env.BRANCH_NAME }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:firefox-${{ env.BRANCH_NAME }}
          cache-to: type=inline
